
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/cronet/url_request_context_config.h

package org.chromium.net.impl;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    HttpCacheType.DISABLED, HttpCacheType.DISK, HttpCacheType.MEMORY
})
@Retention(RetentionPolicy.SOURCE)
public @interface HttpCacheType {
  /**
   * No HTTP cache.
   */
  int DISABLED = 0;
  /**
   * HTTP cache persisted to disk.
   */
  int DISK = 1;
  /**
   * HTTP cache kept in memory.
   */
  int MEMORY = 2;
}
