var NAVTREE_DATA =
[ [ "org.chromium.net", "reference/org/chromium/net/package-summary.html", [ [ "Interfaces", null, [ [ "HostResolver", "reference/org/chromium/net/HostResolver.html", null, null, null ] ]
, null, null ], [ "Classes", null, [ [ "CronetEngine", "reference/org/chromium/net/CronetEngine.html", null, null, null ], [ "CronetEngine.Builder", "reference/org/chromium/net/CronetEngine.Builder.html", null, null, null ], [ "CronetEngine.Builder.LibraryLoader", "reference/org/chromium/net/CronetEngine.Builder.LibraryLoader.html", null, null, null ], [ "UploadDataProvider", "reference/org/chromium/net/UploadDataProvider.html", null, null, null ], [ "UploadDataProviders", "reference/org/chromium/net/UploadDataProviders.html", null, null, null ], [ "UploadDataSink", "reference/org/chromium/net/UploadDataSink.html", null, null, null ], [ "UrlRequest", "reference/org/chromium/net/UrlRequest.html", null, null, null ], [ "UrlRequest.Builder", "reference/org/chromium/net/UrlRequest.Builder.html", null, null, null ], [ "UrlRequest.Callback", "reference/org/chromium/net/UrlRequest.Callback.html", null, null, null ], [ "UrlRequest.Status", "reference/org/chromium/net/UrlRequest.Status.html", null, null, null ], [ "UrlRequest.StatusListener", "reference/org/chromium/net/UrlRequest.StatusListener.html", null, null, null ], [ "UrlResponseInfo", "reference/org/chromium/net/UrlResponseInfo.html", null, null, null ], [ "UrlResponseInfo.HeaderBlock", "reference/org/chromium/net/UrlResponseInfo.HeaderBlock.html", null, null, null ] ]
, null, null ], [ "Exceptions", null, [ [ "CallbackException", "reference/org/chromium/net/CallbackException.html", null, null, null ], [ "CronetException", "reference/org/chromium/net/CronetException.html", null, null, null ], [ "InlineExecutionProhibitedException", "reference/org/chromium/net/InlineExecutionProhibitedException.html", null, null, null ], [ "NetworkException", "reference/org/chromium/net/NetworkException.html", null, null, null ], [ "QuicException", "reference/org/chromium/net/QuicException.html", null, null, null ] ]
, null, null ] ]
, null, null ] ]

;

