
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/cronet/android/url_request_error.h

package org.chromium.net.impl;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    UrlRequestError.LISTENER_EXCEPTION_THROWN, UrlRequestError.HOSTNAME_NOT_RESOLVED,
    UrlRequestError.INTERNET_DISCONNECTED, UrlRequestError.NETWORK_CHANGED,
    UrlRequestError.TIMED_OUT, UrlRequestError.CONNECTION_CLOSED,
    UrlRequestError.CONNECTION_TIMED_OUT, UrlRequestError.CONNECTION_REFUSED,
    UrlRequestError.CONNECTION_RESET, UrlRequestError.ADDRESS_UNREACHABLE,
    UrlRequestError.QUIC_PROTOCOL_FAILED, UrlRequestError.OTHER
})
@Retention(RetentionPolicy.SOURCE)
public @interface UrlRequestError {
  int LISTENER_EXCEPTION_THROWN = 0;
  int HOSTNAME_NOT_RESOLVED = 1;
  int INTERNET_DISCONNECTED = 2;
  int NETWORK_CHANGED = 3;
  int TIMED_OUT = 4;
  int CONNECTION_CLOSED = 5;
  int CONNECTION_TIMED_OUT = 6;
  int CONNECTION_REFUSED = 7;
  int CONNECTION_RESET = 8;
  int ADDRESS_UNREACHABLE = 9;
  int QUIC_PROTOCOL_FAILED = 10;
  int OTHER = 11;
}
