
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../net/nqe/network_quality.h

package org.chromium.net;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    RttThroughputValues.INVALID_RTT_THROUGHPUT
})
@Retention(RetentionPolicy.SOURCE)
public @interface RttThroughputValues {
  /**
   * Invalid value.
   */
  int INVALID_RTT_THROUGHPUT = -1;
}
